### ISSUE TITLE
Svelte 3 with routes etc

### ISSUE THREAD

**Issue by marksteven** [ivanhofer/typesafe-i18n-demo-svelte#1]
Hi Ivanhofer,
THankyou for this wonderful example of svelte with i18n languages.
I am currently just started learning svelte from React and using svelte 3.0.
With the there are bunch of big changes mostly around routes and then folders with 
+page.svelte pages in them.
Do you have some idea of how to implement your i18n version with this new way of doing things?
thank you in advance
Mark

**Comment by ivanhofer** [comment]
Hi @marksteven, I guess you are referring to Sveltekit and are looking for this example: https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit

**Comment by marksteven** [comment]
Mate! Thankyou, you are a legend! Thank you very much. Look forward to learning this new method.
